#!/bin/bash

# TODO: read these from a config file or cli arguments
IFACE=eth0            # the interface that captive portal protects
IP_ADDRESS=10.0.0.10  # the ip address of the captive portal (it can be the IP of IFACE) 


# Allow TCP DNS
iptables -A FORWARD -i ${IFACE} -p tcp --dport 53 -j ACCEPT
# Allow UDP DNS
iptables -A FORWARD -i ${IFACE} -p udp --dport 53 -j ACCEPT
# Allow HTTP and HTTPS traffic to captive portal
iptables -A FORWARD -i ${IFACE} -p tcp -m multiport --dports 80,443 -d ${IP_ADDRESS} -j ACCEPT
# Block all other traffic
iptables -A FORWARD -i ${IFACE} -j DROP
# Redirect other HTTP traffic to captive portal (can't redirect HTTPS traffic, since the cert would be invalid)
iptables -t nat -A PREROUTING -i ${IFACE} -p tcp --dport 80 -j DNAT --to-destination ${IP_ADDRESS}:80
